### ISSUE TITLE
[1.12.2] Mod causes long entities to be stretched and squashed

### ISSUE THREAD

**Issue by MorzanTLD** [CammiePone/ArtemisLib#4]
This mod without any other mods causes mobs like pigs or spiders to become long and squashed.

An example is provided below
![2019-03-30_01 59 59](https://user-images.githubusercontent.com/39711384/55269845-b90dc880-528f-11e9-8bf8-0b6d1d0aea86.png)

**Comment by CammiePone** [comment]
Are you using both attributes, for height and width?

**Comment by CammiePone** [comment]
Fixed the bug
