### ISSUE TITLE
[1.12.2] Rendering is... kinda broken + GL Error log spam.

### ISSUE THREAD

**Issue by SonicX8000** [CammiePone/ArtemisLib#5]
Minecraft: 1.12.2
Forge: 14.23.5.2824

Mods: 1
ArtemisLib-1.12.2-v1.0.4

-----

![](https://cdn.discordapp.com/attachments/377171551155650560/561543990185426947/ArtemisLibGLBroken.PNG)
By kinda broken I mean the water doesn't render, the player & mobs will flash / disappear, particles won't render... etc. Depends on where you look.

![](https://cdn.discordapp.com/attachments/377171551155650560/561544012670959626/ArtemisLibGLBrokenLog.PNG)
Also... the log gets spammed with GL Errors endlessly unless you look at a certain angle.

**Comment by CammiePone** [comment]
Ahhhhhhhhhhhhhh I think I know the problem, and I can't believe I'm such an idiot to not fix it.

**Comment by SonicX8000** [comment]
Looks to be fixed now, if anything else happens I'll let you know.

**Comment by CammiePone** [comment]
Alrighty!~
