### ISSUE TITLE
[1.12.2] Conflict with Trinkets & Baubles. Unable to use Flight via the Ring of Fairies.

### ISSUE THREAD

**Issue by SonicX8000** [CammiePone/ArtemisLib#6]
Minecraft: 1.12.2
Forge: 14.23.5.2824

Mods: 3
ArtemisLib-1.12.2-v1.0.4
Baubles-1.12-1.5.2
Trinkets+and+Baubles-1.12.2-0.23

-----

Ring of Fairies is a Ring Bauble which... while worn... you will slowly shrink down in size and grants you the 'flight' ability. The drawbacks? You cannot jump well and you can only climb up 1 full block.

![](https://cdn.discordapp.com/attachments/377171551155650560/563843493039046686/ringoffairiesbrokenart.PNG)
If ArtemisLib is installed and you equip the ring... you instant-shrink down and no wings render and you're unable to use the 'flight' ability.

![](https://cdn.discordapp.com/attachments/377171551155650560/563843238675480616/ringoffairiesworkingnoart.PNG)
If ArtemisLib isn't installed and you equip the ring, you slowly shrink down, you get some wings on your back and you're able to use the 'flight' ability.

![](https://cdn.discordapp.com/attachments/377171551155650560/563843586429419540/ringoffairiesworntheninstallart.PNG)
Here's a strange thing...  if you have the ring equipped, exit the world and install ArtemisLib and reopen the world... your size returns to normal, the wings render and you're able to fly around. At that point the ring then works correctly by un-equipping & re-equipping it, reopening the world. The only thing is that you instant-shrink down instead of the slow shrink down.

Perhaps since both mods does something with resizing the model/hitbox it conflicts with each other?

**Comment by CammiePone** [comment]
@XzeroAir this one's on you, buddy. It appears something we did with ArtemisLib broke the compat you had with Trinkets and Baubles.

**Comment by XzeroAir** [comment]
Yeah, It's Probably something I Did When I Added ArtemisLib Support, I'll Make sure to look into it tonight, Also, Thank you For the Report

**Comment by SonicX8000** [comment]
No problem.

**Comment by XzeroAir** [comment]
Alright, Yeah, the Issue was on Trinkets and Baubles End, I Figured out the cause, I'll Try to get a Fix out Tonight or Tomorrow

**Comment by SonicX8000** [comment]
The bug has been fixed in "Trinkets and Baubles 0.24". If anything else should come up... I'll let you know.
